package cn.com.webxml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12
 * Wed Nov 28 11:56:24 GMT+08:00 2018
 * Generated source version: 2.2.12
 * 
 */
 
@WebService(targetNamespace = "http://webxml.com.cn/", name = "TraditionalSimplifiedWebServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TraditionalSimplifiedWebServiceHttpPost {

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://webxml.com.cn/", partName = "Body")
    public java.lang.String toTraditionalChinese(
        @WebParam(partName = "sText", name = "sText", targetNamespace = "")
        java.lang.String sText
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://webxml.com.cn/", partName = "Body")
    public java.lang.String toSimplifiedChinese(
        @WebParam(partName = "sText", name = "sText", targetNamespace = "")
        java.lang.String sText
    );
}
