package cn.com.webxml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12
 * Wed Nov 28 11:56:24 GMT+08:00 2018
 * Generated source version: 2.2.12
 * 
 */
 
@WebService(targetNamespace = "http://webxml.com.cn/", name = "TraditionalSimplifiedWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TraditionalSimplifiedWebServiceSoap {

    @WebMethod(action = "http://webxml.com.cn/toTraditionalChinese")
    @RequestWrapper(localName = "toTraditionalChinese", targetNamespace = "http://webxml.com.cn/", className = "cn.com.webxml.ToTraditionalChinese")
    @ResponseWrapper(localName = "toTraditionalChineseResponse", targetNamespace = "http://webxml.com.cn/", className = "cn.com.webxml.ToTraditionalChineseResponse")
    @WebResult(name = "toTraditionalChineseResult", targetNamespace = "http://webxml.com.cn/")
    public java.lang.String toTraditionalChinese(
        @WebParam(name = "sText", targetNamespace = "http://webxml.com.cn/")
        java.lang.String sText
    );

    @WebMethod(action = "http://webxml.com.cn/toSimplifiedChinese")
    @RequestWrapper(localName = "toSimplifiedChinese", targetNamespace = "http://webxml.com.cn/", className = "cn.com.webxml.ToSimplifiedChinese")
    @ResponseWrapper(localName = "toSimplifiedChineseResponse", targetNamespace = "http://webxml.com.cn/", className = "cn.com.webxml.ToSimplifiedChineseResponse")
    @WebResult(name = "toSimplifiedChineseResult", targetNamespace = "http://webxml.com.cn/")
    public java.lang.String toSimplifiedChinese(
        @WebParam(name = "sText", targetNamespace = "http://webxml.com.cn/")
        java.lang.String sText
    );
}
